spring: # Spring Configuration
    datasource: # Connection with database
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
        username: ${DB_USER:salas}
        password: ${DB_PASSWORD:S4l4sInf0*}
        driver-class-name: org.postgresql.Driver
        hikari:
            schema: salasinfo

    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        database: postgresql

server:
    servlet:
        context-path: ${APP_PATH:/salasinfo}
    port: 8090

logging:
    level:
        web: trace
        org:
            springframework:
                web: trace

